### ISSUE TITLE
Please provide an example cube

### ISSUE THREAD

**Issue by AlexHenderson** [zazuko/cube-viewer#15]
Hi, 

Firstly this looks very interesting. :)

Is it possible to provide an example SPARQL endpoint so we can run the demo viewer at https://cube-viewer.zazuko.com/ 

Thanks,
Alex

**Comment by ktk** [comment]
Hi Alex,

Yes it would make sense to have a default endpoint, meanwhile try `https://lindas.admin.ch/query`. Try one of the cubes in the `energy.ld.admin.ch` namespace, they have the best metadata.
