### ISSUE TITLE
Show labels for dimensions

### ISSUE THREAD

**Issue by ktk** [zazuko/cube-viewer#3]
I would like to see labels instead of IRIs for entries in the cube, currently it shows a shortened IRI. It should look like what I would get with a standard "Excel" like view.

It is ok if I would have to turn a switch for that as it might have to dereference a lot of IRIs for triples outside the local store.

**Comment by martinmaillard** [comment]
cube-viewer reflects the feature available in rdf-cube-view-library. Once we have a documented way of loading labels in the library, I'll be able to implement it in cube-viewer.
