### ISSUE TITLE
Load materialized view

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-viewer#5]
A [cube view](https://github.com/zazuko/rdf-cube-view-query#view) can be stored as RDF in a store. It should be possible to point cube-viewer to the URI of a view to load it.

- A view has `rdf:type cube:View`
- Cube-viewer is already using a view. It's building it with `const view = View.fromCube(cube.value.data)`. It should be possible to build a view from a clownface pointer.

**Comment by martinmaillard** [comment]
@bergos Do you already have a view stored somewhere? That would help a lot.
If not that's ok, I'll setup something locally.

**Comment by bergos** [comment]
@martinmaillard we prepared two for zuerich:

https://ld.stadt-zuerich.ch/statistics/view/V000001/
https://ld.stadt-zuerich.ch/statistics/view/V000003/

**Comment by martinmaillard** [comment]
I think the cube library needs a way to fetch a view with its URL. Something like `source.view(term)`.

**Comment by ktk** [comment]
@cristianvasquez IMO this is what we did now. Please re-read issue & close when ok.

**Comment by cristianvasquez** [comment]
@ktk , yes the merge enables precisely this. I'll close the issue now
